language: rust
rust: 1.46.0
dist: xenial
sudo: true
cache:
  directories:
    - $HOME/.cargo
  timeout: 1024

git:
  depth: 2
  submodules: false

env:
  global:
    - RUST_BACKTRACE=full
    - CKB_CLI_VERSION=v0.39.0

addons:
  apt:
    sources:
      - sourceline: "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main"
        key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    packages:
      - libssl-dev
      - autoconf
      - flex
      - bison
      - texinfo
      - libtool
      - clang-8
      - libc6-dev-i386
      - expect

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ulimit -n 8192; fi

script: make test

before_cache:
  - rm -rf $HOME/.cargo/registry

if: 'tag IS NOT present and (type != pull_request or head_branch != develop)'

matrix:
  allow_failures:
    - rust: stable
  include:
    - name: Integration on macOS
      os: osx
      script: make CKB_TEST_ARGS="-c 1 --no-report" integration
    - name: Integration on Linux
      os: linux
      script: make CKB_TEST_ARGS="--max-time 1200 -c 1 --no-report" integration
